name: easy_forms_validation
homepage: https://github.com/jarekb123/easy_forms
description: A Dart library that provides a mixin for form validation logic, allowing for easy validation of form data and management of form field validation state.
version: 0.3.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
